package bms.protocol;


public enum RequestType {
    LOGIN_DEVELOPER, LOGIN_TESTER, LOGOUT_DEVELOPER, LOGOUT_TESTER, ADD_BUG, REMOVE_BUG, GET_BUGS, GET_UNSOLVED_BUGS, SOLVE_BUG, GET_UNSOLVED_BUGS_BY_TESTER;
}
